[package]
name = "aws-lambda-runtime-api-inspector"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
aws-lambda-runtime-proxy = "0.2.1"
http-body-util = "0.1.1"
http = "1.1.0"
